package com.humanresourcemanagementsystem.Entity;

import jakarta.persistence.*;

import java.util.Date;

@Entity
//Mapping of Education class to database table hrm_education
@Table(name = "hrm_education")
public class Education {

    //Education id is a primary key and is autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "education_id")
    private int education_id;

    //One person can have multiple educations
    @ManyToOne
    @JoinColumn(name = "person_id", referencedColumnName = "person_id")
    private Person person;

    //One employee can have multiple educations
    @ManyToOne
    @JoinColumn(name = "employee_id", referencedColumnName = "employee_id")
    private Employee employee;

    @Column(name = "degree", nullable = false)
    private String degree;

    @Column(name = "institution", nullable = false , unique = true)
    private String institution;

    @Column(name = "major", nullable = false , unique = true)
    private String major;

    @Column(name = "graduation_start_date")
    private Date graduation_start_date;

    @Column(name = "graduation_end_date")
    private Date graduation_end_date;

    @Column(name = "created_at", updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date created_at;

    @Column(name = "updated_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updated_at;

    // Default constructor initializes created at and updated at field with current date
    public Education() {
        this.created_at = new Date();
        this.updated_at= new Date();
    }

    //Parameterized constructor initializes all fields with provided values
    public Education(int education_id, Person person, Employee employee, String degree, String institution, String major, Date graduation_start_date, Date graduation_end_date, Date created_at, Date updated_at) {
        this.education_id = education_id;
        this.person = person;
        this.employee = employee;
        this.degree = degree;
        this.institution = institution;
        this.major = major;
        this.graduation_start_date = graduation_start_date;
        this.graduation_end_date = graduation_end_date;
        this.created_at = created_at;
        this.updated_at = updated_at;
    }

    // Getter and Setter provide access to the private fields
    public int getEducation_id() {
        return education_id;
    }

    public void setEducation_id(int education_id) {
        this.education_id = education_id;
    }

    public int getPerson() {
        return person.getPersonID();
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getInstitution() {
        return institution;
    }

    public void setInstitution(String institution) {
        this.institution = institution;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    public Date getGraduation_start_date() {
        return graduation_start_date;
    }

    public void setGraduation_start_date(Date graduation_start_date) {
        this.graduation_start_date = graduation_start_date;
    }

    public Date getGraduation_end_date() {
        return graduation_end_date;
    }

    public void setGraduation_end_date(Date graduation_end_date) {
        this.graduation_end_date = graduation_end_date;
    }

    public Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    public Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}

