package com.humanresourcemanagementsystem.Entity;

import jakarta.persistence.*;
import java.util.Date;

@Entity
//Mapping of Vacation class to database table hrm_vacation
@Table(name = "hrm_vacation")
public class Vacation {

    @Id
    //Vacation id is a primary key and is autogenerated
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int vacation_id;

    //One Employee can have many vacations
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", referencedColumnName = "employee_id")
    private Employee employee;

    @Column(name = "start_date")
    private Date startDate;

    @Column(name = "end_date")
    private Date endDate;

    private String reason;
    private String status;

    @Column(name = "vacation_type")
    private String vacationType;

    @Column(name = "created_at", updatable = false, nullable = false)
    private Date createdAt;

    @Column(name = "updated_at", nullable = false)
    private Date updatedAt;

    // Default constructor initializes created at and updated at field with current date
    @PrePersist
    protected void onCreate() {
        createdAt = new Date();
        updatedAt = new Date();
    }

    //Parameterized constructor initializes all fields with provided values
    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Date();
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public int getVacationId() {
        return vacation_id;
    }

    public void setVacationId(int vacation_id) {
        this.vacation_id = vacation_id;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getVacationType() {
        return vacationType;
    }

    public void setVacationType(String vacationType) {
        this.vacationType = vacationType;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}